### PR TITLE
Preparation for getting the latest changes for Grease into the master branch --- SeasideSt/Grease 1.3

### PR DESCRIPTION
**Pull request by dalehenrich**
Hold off a minute while @marschall figures out if the GRSmalltalkDictionary changes are okay

### CODE REVIEW

**Comment by jbrichau** [comment]
@dalehenrich @marschall I made a pre-release 1.3.0 on the master branch of SeasideSt/Grease.
I was thinking about sending in a pull request such that GemStone will use latest Grease.

Then I hit this one. Can you update me on the status? All tests are green on the master repo, which is including Gemstone. (https://github.com/SeasideSt/Grease)

I did not follow up on your work at ESUG sprint, but I want to pick up the ball here to release a new Seaside version when we can. Hence, first a new Grease.

Hope you can still remember something :)

**Comment by dalehenrich** [comment]
I've been using the dev branch of Grease for a very long time ... so I don't have a problem with merging this into the master, but I will wait for @marschall to chime in then we can integrate your changes as well ... @jbrichau inthe mean time, I will pull your changes into the dev branch and see what happens ...

**Comment by dalehenrich** [comment]
We'll let travis run the tests; @jbrichau the non-mc conflict was in .travis.yml and I chose to use yours

**Comment by dalehenrich** [comment]
Looking at the timestamp for the original comment in this PR and the timestamp of @marschall second synch (harder than I'd like, but at leat possible) ... the synch comes after the pr was opened, so we **did** get the latest code from Phillippe :) .... I'll pull the trigger on the merge

**Comment by dalehenrich** [comment]
@jbrichau I just noticed that 1.3 is marked as pre-release ./... Is that because you are waiting for integration of this PR --- which now includes [SeasideSt/Grease 1.3](https://github.com/SeasideSt/Grease/releases/tag/v1.3.0)?

**Comment by jbrichau** [comment]
@dalehenrich I was unsure if some more commits were going to be necessary before making it a final 1.3.0 

Mostly because I was unsure about the state of the Gemstone fork and the comments in here. Also: the smalltalkhub repository does not know about 1.3.0 and the ConfigurationOfGrease does not yet reference this repo.

I think I will start referencing the github repo for Grease and let that one be the master. So, once I committed the ConfigurationOfGrease with a reference to github, I mark it as final release.

Since the GsDevKit / GLASS universe references the GsDevKit/Grease repo, you're welcome to advance master now or after the final release.

**Comment by dalehenrich** [comment]
I'll wait on the final release to push the dev branch to master, but until then this PR will accumulate the changes that you make on your master branch ... unless something comes up along the way

**Comment by jbrichau** [comment]
@dalehenrich I added one more commit on SeasideSt/Grease:master and marked the 1.3.0 as release. I do not see the commit popping up here though...
In any case, I think it's a go.

**Comment by dalehenrich** [comment]
ah, my bad ... this PR is on the dev branch in this project ... I'll need to create another PR ...

**Pull request merged**
