### PR TITLE
straight up comparison between the two reops

### PR DESCRIPTION
**Pull request by dalehenrich**

### CODE REVIEW

**Comment by dalehenrich** [comment]
My GsDevKIt_home runs that were run using SeasideSt/Grease directly is running green so the upgrade tests are passing ... the final thing that I think I need to do is verify that and upgrade from a stone built with the old Grease packages can be upgraded to the new Grease packages (after this PR is merged) and I need to set up a custom test for that ... getting real close

**Comment by dalehenrich** [comment]
@jbrichau ... do I still need to merge this PR? I have successfully run Travis tests, but I still need to create a run a couple of tests that are not easily automated (upgrade of repo with pre-merge Grease into post-merge Grease) ... it's not a test that I usually run --- the upgrade tests assume that you are using the latest GLASS releases on both repos before doing an upgrade, but I realize that is not always done ... so I think it is prudent that I do this kind of testing (at least internally) which implies that I will need more time before I finish that up ...

I'm asking because I saw a message fly by that I think said that "you had merged something into GsDevKit/Grease" and I'm curious if you are thinking that this PR is the merge, or was there another merge done?

As I think more about the new tests, I'm imagining that I can go ahead and pull the trigger on this PR, but I probably want to to sleep on it one more night:)

**Comment by jbrichau** [comment]
It would be good to have GsDevKit use the master Grease version yes, please. I mentioned this PR somewhere as a prerequisite to merge more testing into Seaside. However, I now marked the relevant failing test in Seaside for Gemstone as an expected failure until this gets merged. It’s a test issue but the fix was a missing method in Grease.

**Comment by dalehenrich** [comment]
@jbrichau okay ... good to know that this merge is required ... I'll plan on doing the emerge tomorrow ... after sleeping on it :)

**Comment by jbrichau** [comment]
@dalehenrich the merge conflict points to differences in the packaging I made here: https://github.com/SeasideSt/Grease/commit/9d4fe1af0c5f37cd91434a18f050d0059211a4d5

This was done to ease maintenance, since the 'filename' difference was off-putting tools in Tode. I will fix the baseline with that in mind and if you are happy, you can hit the merge button ;-)

**Comment by dalehenrich** [comment]
[Okay rerunning GsDevKit_home tests using SeasideSt/Grease to validate most recent changes](https://travis-ci.org/github/GsDevKit/GsDevKit_home/builds/757115358)

**Comment by dalehenrich** [comment]
[Looks like the thisContext test is failing for 2.4.x](https://travis-ci.org/github/SeasideSt/Grease/jobs/756957059#L2967). I don't think that it is really necessary to support 2.4.x moving forward ... so removing it from the travis lineup would not be a crime :)

**Comment by jbrichau** [comment]
Haha, indeed. I will just remove that version from the test lineup. 
Getting back to this asap ;-)

**Comment by dalehenrich** [comment]
Haha, and the travis build is still running, but it seems to be passing, so it's looking good ... when travis finishes I will want to manually do a reload from the old version to the new version to see if there are any hiccups (actually I can do this at any time and will when I find the time) ...

**Comment by dalehenrich** [comment]
... oh, my browser hadn't updated ... rerunning the one test that failed ...

**Comment by jbrichau** [comment]
@dalehenrich I added your lineup of gs3.7 to 3.9 to the baseline (future proofness? :-) ). The difference now, besides indentation, is about the last statement:

```
	spec
		for:
			#(#'gs3.2.x' #'gs3.3.x' #'gs3.4.x' #'gs3.5.x' #'gs3.6.x' #'gs3.7.x' #'gs3.8.x' #'gs3.9.x')
		do: [ 
			spec
				package: 'Grease-Tests-GemStone-Core'
				with: [ spec file: 'Grease-Tests-GemStone-Core.v32' ] ]
```
vs
```
spec
    for: #(#'gs3.2.x' #'gs3.3.x' #'gs3.4.x' #'gs3.5.x' #'gs3.6.x')
    do: [ 
      spec
        package: 'Grease-Tests-GemStone32-Core'
		    with:[ spec requires: 'Grease-Tests-Core' ];
		  package: 'Grease-Tests-Core'
        	 with: [ spec includes: 'Grease-Tests-GemStone32-Core' ] ]
```
This is the change I referred to [earlier](https://github.com/GsDevKit/Grease/pull/17#issuecomment-770415209).

Unless you see issues with that, I will just push the baseline of SeasideSt/Grease

**Comment by dalehenrich** [comment]
I guess, I can't tell quite what you are doing ... Removing the package 'Grease-Tests-GemStone32-Core'? ... If things are working correctly then I suppose it is cool :)

**Comment by jbrichau** [comment]
I added it :)
It used to be done with that ‘file:’ message.

**Comment by dalehenrich** [comment]
I just did a test load of SeasideSt/Grease:gsdevkit-merge into a 3.6.0 stone with GsDevKit/Grease:master loaded and it loaded without error (yeah!), when I looked at `baselineGemStone:` , I saw the following:
```
	spec
		for:
			#(#'gs3.2.x' #'gs3.3.x' #'gs3.4.x' #'gs3.5.x' #'gs3.6.x' #'gs3.7.x' #'gs3.8.x' #'gs3.9.x')
		do: [ 
			spec
				package: 'Grease-Tests-GemStone32-Core'
					with: [ spec requires: 'Grease-Tests-Core' ];
				package: 'Grease-Tests-Core'
					with: [ spec includes: 'Grease-Tests-GemStone32-Core' ] ]
```
Other than the fact that I thought that you had done the opposite :) 

I ran the tests and they are all green, so merge away ...

**Pull request merged**
