### PR TITLE
Fix for GRDynamicVariable

### PR DESCRIPTION
**Pull request by jbrichau**
Grease 1.3.2 fixes bugs in the implementation of GRDynamicVariable in GemStone.

If we can have this one used in GsDevKit/GLASS, then at least the tests for Seaside develop will work again in GemStone.

### CODE REVIEW

**Comment by jbrichau** [comment]
@dalehenrich speaking of Grease ;) Do you think this one can be merged?

**Comment by dalehenrich** [comment]
What about the test failures for Squeak5.1? are those expected errors?

**Comment by jbrichau** [comment]
(now doing this from github, so pretty sure it's the right thread.... )

Yes, these are Slime tests that started failing some weeks ago without changes in Grease itself. So, I propose to ignore them here.

**Comment by dalehenrich** [comment]
see [this comment](https://github.com/Metacello/metacello/pull/450#issuecomment-330600051) where @jbrichau gives his blessing to ignored the Squeak5.1 failures ...

**Comment by dalehenrich** [comment]
@jbrichau you might consider moving Squeak5.1 into expected failures for travis so that we can record that Squeak5.1 is not expected to pass

**Pull request merged**
