### PR TITLE
Grease v1.10

### PR DESCRIPTION
**Pull request by jbrichau**
Update GsDevKit Grease to finalize support for:
- latest Seaside-Gettext port to GemStone (pending in https://github.com/SeasideSt/Seaside/tree/gettext-fix until this gets merged)
- Zinc request streaming work (https://github.com/SeasideSt/Seaside/pull/1196)

### CODE REVIEW

**Comment by dalehenrich** [comment]
@jbrichau, looks like only the pharo tests are failing .... are they important? Perhaps they should be removed, so green means green ...

**Comment by jbrichau** [comment]
@dalehenrich I think the build is coloring red because of the failing 'post to slack' step. The Pharo 11 and Squeak builds are marked as experimental. The build is green over at SeasideSt: https://github.com/SeasideSt/Grease/actions/runs/2724711470 

Perhaps something changed in the Slack integration?

**Comment by dalehenrich** [comment]
ah, so those guys are expected failures? I'm seeing the messages in slack (so the error must not be a "real error"? .. I wouldn't see the messages in slack if there was an invalid webhook id ... I even am getting two copies of the slack messages --- but in slack that they've decided not to ignore) ... It's not as easy with guthub actions to see immediately see that an action is an expected failure ... 

If they are expected failures then the red boys can be ignored ...

**Comment by dalehenrich** [comment]
Okay it looks like [Pharo64-11 is NOT marked as experimental ... Pharo64-10 IS experimental](https://github.com/GsDevKit/Grease/blob/master/.github/workflows/ci.yml#L22-L23) ... so that's why the action is failing... could you make the change on your pull request? I think that's easier for you to do ...

**Comment by jbrichau** [comment]
@dalehenrich I'm not sure what's causing the confusion. This PR does change it as such: https://github.com/GsDevKit/Grease/pull/25/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f

**Comment by dalehenrich** [comment]
Okay ... then I suppose this just might be a github action issue then (using the old version of the .yml to run the new stuff...) ... I'll go ahead and merge the request and try rerunning the tests to see if it works afterwards ...

**Comment by dalehenrich** [comment]
I'm going blind, I don't see in the diff where pharo-11 was added to the list?

**Comment by jbrichau** [comment]
@dalehenrich hold on, I'll get to my laptop and check before you merge to make sure ;-)

**Comment by dalehenrich** [comment]
I thought it needed to be in the list ... but maybe not ... YAML is not my strong suit :)

**Comment by jbrichau** [comment]
Discussed on Slack: it's good to go.
I'll check if I can find a solution to the Slack post step since we prefer real green, of course ;-)

**Pull request merged**
