### PR TITLE
Sync GsDevKit/Grease with changes in SeasideSt/Grease

### PR DESCRIPTION
**Pull request by jbrichau**
For Gemstone, the following changes have occurred:
- Monticello metadata removal
- Added Symbol>>greaseAsMutator (as a Grease abstraction for Symbol>>asMutator)

### CODE REVIEW

**Comment by dalehenrich** [comment]
@jbrichau I see that this PR is hitting the bug in 3.5.1/3.5.2 that appeared just recently (#105) ... since there have been earlier tests that have passed against 3.5.1/3.5.2 I'm not exactly sure where the change has been made that is causing the failure ... and I have not had the cycles to spend the time to track this problem down ...and it only seems to affect the Grease travis builds ... also it seems that the change was introduced between a month and 20 days ago .... 

[GsDevKit/Grease tests passed 2 months ago agains 3.5.1](https://travis-ci.org/github/GsDevKit/Grease/builds/685385426) and stated failing [19 days ago against 3.5.1](https://travis-ci.org/github/GsDevKit/Grease/builds/696955022).

[Seaside tests failed a day ago with same error against 3.5.2](https://travis-ci.org/github/SeasideSt/Seaside/builds/702844307) and [passed 26 days ago against 3.5.0](https://travis-ci.org/github/SeasideSt/Seaside/builds/694300222).

Stiil looking a bit ... do you have any ideas what may have changed?

**Comment by dalehenrich** [comment]
[here's a passing GsDevKit_home 3.5.1build](https://travis-ci.org/github/GsDevKit/GsDevKit_home/jobs/702544543) that ran three days ago that did a build with [GsDevKit/Grease master branch](https://travis-ci.org/github/GsDevKit/GsDevKit_home/jobs/702544543#L1219-L1239) without a build failure.... which is now very odd ...

**Comment by dalehenrich** [comment]
Turns out that the failure is actually occurring while SmalltalkCI is being loaded into the stone, which implies that this is a SmalltalkCI regression/bug

**Comment by jbrichau** [comment]
After fixing https://github.com/SeasideSt/Grease/issues/105 all is well!

**Pull request merged**
